#!/bin/bash

# GLOBAL HELPER FUNCTIONS

err() {
    echo "$@" 1>&2
}

# FUNCTION COMMAND DECLARATION
init() {
    echo init
}

uninit() {
    echo uninit
}

set() {
    echo set
}

push() {
    echo push
}

pull() {
    echo pull
}

help() {
    echo help
}

# Handle no args
if [ $# -eq 0 ]; then
    help
    exit 0
else
    cmd="$1"
fi # Post: Args were passed

# Forward command
shift
case "$cmd" in
    init)   init "$@" ;;
    uninit) uninit "$@" ;;
    set)    set "$@" ;;
    push)   push "$@" ;;
    pull)   pull "$@" ;;
    help)   help "$@" ;;
    *)      err "Error: Invalid command: $cmd"
esac
